name: Generate Weekly Summary

on:
  repository_dispatch:
    types: [generate-note]
  workflow_dispatch:  # 手動実行も可能

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          npm list tsx
          
      - name: Generate weekly summary
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_OUTPUT_DATABASE_ID: ${{ secrets.NOTION_OUTPUT_DATABASE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Running generate-note script..."
          npx tsx scripts/generateNoteArticle.ts 